### PR TITLE
fix the bug of rnn

### PR DESCRIPTION
**Pull request by pppku**

### CODE REVIEW

**Comment by ftshijt** [comment]
I do not understand, why change the name?

**Comment by pppku** [comment]
> I do not understand, why change the name?

There are some unknown conflicts that cause wavrnn can't work.

**Comment by pppku** [comment]
> I do not understand, why change the name?

I fix it on my own project so that I can work normally, but it's indeed a bug. When my train is over I will fix and test it.

**Comment by ftshijt** [comment]
Please fix the CI then I will merge it

**Comment by ftshijt** [comment]
I believe the `prepare_data.py` for each database should also have some changes for the wavernn?

**Comment by ftshijt** [comment]
Oh, I saw it in the recipe. LGTM!

**Pull request merged**
